server:
  port: 8080
spring:
  application:
    name: <name>
  datasource:
    url: <database-url>
    username: <username>
    password: <password>
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <google-client-id>
            client-secret: <google-client-secret>
            scope:
              - email
              - profile
          github:
            client-id: <github-client-id>
            client-secret: <github-client-secret>
            scope:
              - read:user
              - user:email
      success:
        redirect:
          uri: http://localhost:5173/oauth2/success
      failure:
        redirect:
          uri: http://localhost:5173/oauth2/failure
jwt:
  access:
    token:
      secret: <jwt-access-token-secret>
      expiration: <access-token-expiration>
  refresh:
    token:
      secret: <jwt-refresh-token-secret>
      expiration: <refresh-token-expiration>