server:
  port: 8080

spring:
  application:
    name: auth
  datasource:
    # Replace <jdbc-url> with your actual JDBC URL
    url: <jdbc-url>
    # Replace <username> with your actual username
    username: <username>
    # Replace <password> with your actual password
    password: <password>
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true