server:
  port: 8080

spring:
  application:
    name: auth
  datasource:
    url: <jdbc-url>
    username: <db-username>
    password: <db-password>
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <google-client-id>
            client-secret: <google-client-secret>
            scope:
              - email
              - profile
          github:
            client-id: <github-client-id>
            client-secret: <github-client-secret>
            scope:
              - read:user
              - user:email
      success:
        redirect:
          uri: <on-success-redirect-uri>
      failure:
        redirect:
          uri: <on-failure-redirect-uri>
      github:
        users:
          email:
            url: https://api.github.com/user/emails
  cloud:
    openfeign:
      circuit-breaker:
        enabled: true
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
jwt:
  access:
    token:
      secret: <access-token-secret>
      expiration: <access-token-expiration-in-ms>
  refresh:
    token:
      secret: <refresh-token-secret>
      expiration: <refresh-token-expiration-in-ms>
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: <eureka-server-url>
info:
  app:
    name: auth
    description: Eventer Auth Microservice
    version: 1.0.0